### PR TITLE
[New Component] - MudTextM3

### PR DESCRIPTION
**Pull request by segfault-**
Initial creation of MudTextM3 based on material 3 typography specifications - https://m3.material.io/styles/typography/overview

image

image

### CODE REVIEW

**Comment by mckaragoz** [comment]
Thanks for the PR. Have two opinions.

1. What about using "Typo" and "Size" as parameter names?

2. We need to arrange API page also for the new component. And in drawer's nav menu, components should be in alphabetical order.

**Comment by segfault-** [comment]
> Thanks for the PR. Have two opinions.
> 
> 1. What about using "Typo" and "Size" as parameter names?
> 2. We need to arrange API page also for the new component. And in drawer's nav menu, components should be in alphabetical order.

I’ll amend my pr with these items

**Comment by segfault-** [comment]
checked in changes based on review, let me know if any additional changes are required

**Comment by mckaragoz** [comment]
> checked in changes based on review, let me know if any additional changes are required

Thanks, really good effort. I would only say, we can enhance the docs. We can seperate typo into groups and users can easily show which ones are `Display` or `Body` one with a label.

**Comment by mckaragoz** [comment]
Sorry i didn't see the second picture. Thanks again 🥇

**Pull request merged**
