### PR TITLE
Fix issue #275: Description of the changes made

### PR DESCRIPTION
**Pull request by PrimeJoker**
- Use the same Delimeter selected to output data file. #275

### CODE REVIEW

**Comment by PrimeJoker** [comment]
@mckaragoz new PR, let me know if it's all okay. Cheers.

**Comment by mckaragoz** [comment]
Could you also fix the typo?

**Comment by PrimeJoker** [comment]
@mckaragoz type fixed too. Cheers.

**Comment by mckaragoz** [comment]
Thanks 🥇

**Pull request merged**
