### PR TITLE
Add a search string change event

### PR DESCRIPTION
**Pull request by mo3ayka**
In some of our cases, we need to be able to receive a signal about a search change, so I would like to suggest adding an event

### CODE REVIEW

**Comment by mckaragoz** [comment]
Actually, you have `SearchFunc` parameter that you can do whatever you want when search string changed. Do you have something that you can't do in SearchFunc?

**Comment by mo3ayka** [comment]
Yes, I tried to use it, but with its help there is no way to know when the search will be finished. We need to know when the search started, the user entered some character and when the user clear the search value
https://github.com/CodeBeamOrg/CodeBeam.MudBlazor.Extensions/blob/7ccb9f635e434a3ff246d632a5eb021d7e46aeb6/CodeBeam.MudBlazor.Extensions/Components/ListExtended/MudListExtended.razor.cs#L1422

If the search string is empty, then SearchFunc is not called

**Comment by mckaragoz** [comment]
Understand.

The only thing is SomethingChanged is two way bind pattern in Blazor.

We should use `OnSearchStringChange` instead of `SearchStringChanged`

**Comment by mo3ayka** [comment]
> We should use `OnSearchStringChange` instead of `SearchStringChanged`

I fixed it 🙂

**Comment by mckaragoz** [comment]
> > We should use `OnSearchStringChange` instead of `SearchStringChanged`
> 
> I fixed it 🙂
> 

Sorry again, not "Changed", should be "Change" :) Blazor understand "Changed" keyword with different meaning.

**Comment by mo3ayka** [comment]
> Blazor understand "Changed" keyword with different meaning.

Wow, I'm learning more and more about the nuances of the blazor, cool 🤯
Fixed it )

**Comment by mckaragoz** [comment]
Thanks 🥇

**Pull request merged**
