### PR TITLE
SelectExtended: Fix overflow of text & adornment

### PR DESCRIPTION
**Pull request by jneufferrpm**
Prevents the adornment from overflowing the input in select extended #457

### CODE REVIEW

**Comment by mckaragoz** [comment]
Did you also try this with chips etc.? There are several visual options in select, we don't want to break one while fixing another one

**Comment by jneufferrpm** [comment]
> Did you also try this with chips etc.? There are several visual options in select, we don't want to break one while fixing another one

I have not tried it with the other visual options such as chips. I will test it tomorrow.

**Comment by jneufferrpm** [comment]
@mckaragoz I have tested some of the other visualization options, Everything seems to work as expected.

### Long text with no wrap

(this is what is fixed by the change)

**Before:**
image

**After: text & adornment overflow fixed**
image

### Chips (still works as expected)
image
image


### Custom content (still works as expected)
image

**Comment by mckaragoz** [comment]
Thanks 🥇

**Pull request merged**
