### PR TITLE
Rename "Delimeter" to Delimiter

### PR DESCRIPTION
**Pull request by PrimeJoker**
- fix the build error "Delimiter" does not exist in the current context. Amend to #274 created.

### CODE REVIEW

**Comment by enkodellc** [comment]
This seems like it is a simple fix.

**Comment by enkodellc** [comment]
@mckaragoz  this looks like it can be merged. It fixes a typo.

**Comment by mckaragoz** [comment]
> @mckaragoz  this looks like it can be merged. It fixes a typo.

Yes it's done, but it's a breaking change. And not obsoleted the old parameter, directly removed.

**Comment by PrimeJoker** [comment]
When do you think it can be pushed live?

**Comment by mckaragoz** [comment]
> When do you think it can be pushed live?

If you can obsolete the old parameter instead of completely remove we can merge it today. But currently it's a direct breaking change, users will have errors after update the package, so we need to wait next major release

**Comment by PrimeJoker** [comment]
@mckaragoz I have reinstated the original parameter name to make it easier to merge pull request.

**Comment by mckaragoz** [comment]
Hi, its now time to fix this typo, could you prepare a new fresh PR?

**Pull request closed without merging**
