### PR TITLE
MudStepper directional logic support for "PreventStepChange"

### PR DESCRIPTION
**Pull request by rhyskoedijk**
`MudStepper.PreventStepChange` now passes a "direction" argument to allow conditional forward/backward logic.

Previously you could not skip validation when navigating backwards, which is _normally_ undesirable.
Now validation can (for example) be enforced when moving forwards, but not backwards.

Using an enum might be overkill here, it was a pretty quick edit.

### Before
mudstepper_before

### After
mudstepper_after

### Migration
This is a code breaking change if you are using `MudStepper.PreventStepChange`.
To migrate, change your function from `Func<bool>` to `Func<StepChangeDirection, bool>`

### CODE REVIEW

**Comment by rhyskoedijk** [comment]
I could also change this to pass the new step index instead of a forward/backward enum. The caller could then calculate the direction change themselves, an enum seemed more user friendly.

**Comment by mckaragoz** [comment]
I think i found a bug there. Could you reproduce this steps:

1. Press next button on first step. (check validation switch is off)
2. Turn on the check validation switch.
3. Press previous button (it turns back to the first step, its ok)
4. Press next button (it should not continue to the next step, but it does)

**Comment by rhyskoedijk** [comment]
Should be fixed now

**Comment by mckaragoz** [comment]
> Should be fixed now

Yeah, but this time i think we have another one.

1. Click on third step (payment one) (or go to third step one by one)
2. Turn on the check validation switch
3. Click on previous button (it should not go to the second step, but it does)

I think a test will be perfect for this prevent logic.

**Comment by rhyskoedijk** [comment]
> 1. Click on third step (payment one) (or go to third step one by one)
> 2. Turn on the check validation switch
> 3. Click on previous button (it should not go to the second step, but it does)

I might be misunderstanding the issue as this is what I expect to happen. In `StepperExample1` my custom logic for `PreventStepChange` always allows stepping backwards regardless of form validation.

````csharp
// Always allow stepping backwards, even if forms are invalid
if (direction == StepChangeDirection.Backward)
{
    return false;
}
````
What the user decides to do here is up to them, this was just an example. I could either change this logic or make the example more clear about this [custom] behavior.

> I think a test will be perfect for this prevent logic.

I have added several unit tests to ensure `PreventStepChange` behaves as expected.

I also made a change to `CompleteStep` and `SkipStep` so that they only invoke `PreventStepChange` and change `ActiveIndex` when completing/skipping the **active step**. Things can get a bit weird if you (for example) are currently on step 1, invoke "complete step 3", which triggers "move from step 1 to step 4". Happy to revert this if I missed something obvious here.

**Comment by mckaragoz** [comment]
Thanks, i feel its not the final PR about prevent, but looking good especially on backward change 🥇

**Pull request merged**
