### PR TITLE
Upgrade to MudBlazor 7.9.0

### PR DESCRIPTION
**Pull request by sfmskywalker**
Converted key bindings to arrays for consistency and updated MudBlazor to version 7.9.0 in project files. Also modified the project version to 7.0.2 in CodeBeam.MudBlazor.Extensions.csproj.

All automated tests are green.

### CODE REVIEW

**Comment by ScarletKuro** [comment]
@mckaragoz We accidentally broke things again https://github.com/MudBlazor/MudBlazor/pull/9896#issuecomment-2407618246 since I did not pay enough attention when it was suggested to do some changes to `KeyInterceptorOptions`.
This change should fix it.
Tho I would suggest to switch to new `IKeyInterceptorService` since the `IKeyInterceptor` is removed in v8. The new API usage you can find here: https://github.com/MudBlazor/MudBlazor/pull/9896

**Comment by ScarletKuro** [comment]
Was fixed in v7.10.0 MudBlazor https://github.com/CodeBeamOrg/CodeBeam.MudBlazor.Extensions/issues/454#issuecomment-2407863022
So this PR is not urgent anymore.

**Comment by sfmskywalker** [comment]
Sweet, then I’ll close this one. Thanks for the fast response and for this awesome library!

**Comment by mckaragoz** [comment]
@ScarletKuro thanks. By the way discord is banned in Turkey, If you have notifications for me please do it on GitHub in these days :)

**Comment by ScarletKuro** [comment]
> @ScarletKuro thanks. By the way discord is banned in Turkey, If you have notifications for me please do it on GitHub in these days :)

Interesting. Hope you will get VPN.

**Pull request closed without merging**
