### PR TITLE
Added ability to set Select All checkbox positions

### PR DESCRIPTION
**Pull request by sabitertan**

### CODE REVIEW

**Comment by mckaragoz** [comment]
Good idea. While doing this, could you add also `AfterSearchBox` and `End` values to `SelectAllPosition`?

**Comment by mckaragoz** [comment]
Thanks for new commits. Did you remove "nextto" one, i liked it 🙂

**Comment by sabitertan** [comment]
No I renamed it to "BeforeSearch" :)

**Comment by sabitertan** [comment]
are these the positions you are looking for : 
image

Please let me know if you imagined something else :)

**Comment by mckaragoz** [comment]
Hmm, i thought SelectAll also has sticky position. If it doesn't have we don't need to bottom 🙂 

I think this 3 one is sufficient:

1. BeforeSearchBox: Upper line
2. NextToSearchBox: Start of the searchbox in the same line
3. AfterSearchBox: Below line

**Comment by mckaragoz** [comment]
Thanks 🥇

**Pull request merged**
